// GENERATED CODE - DO NOT MODIFY BY HAND
// -----------------------------------------------------------------------------
//  This file is auto-generated by asset_gen.dart
//  Do not make manual changes. Regenerate by running the generator script.
//  Last Created: 2025-07-08 17:02:36.069697
// -----------------------------------------------------------------------------

class AppAssets {
  /// Path to 'assets/image/xyz.png'.
  static const String assetsImageXyz = 'assets/image/xyz.png';
}
